### ISSUE TITLE
Iasue with crystal reconstructor sphere

### ISSUE THREAD

**Issue by trickyspider** [jinxOAO/DSPmod_MoreMegaStructures#34]
I have a crystal reconstructer sphere made and I have the correct recivers made, and set to substance generation
The output says type not match and it's never outputting anything 
![20240516_104600](https://github.com/jinxOAO/DSPmod_MoreMegaStructures/assets/170022303/cc76ca1b-557f-4891-a788-1fb6e0147810)

**Comment by jinxOAO** [comment]
Will you please send me the log file?
Seems that the product Id is not correctly set for the new receivers, since the correct product will be potical crystal rather than critic photon (which is the reason why it says "type not match"). 
Do other receivers work properly? I think there may be some errors in the preload phase.

**Comment by jinxOAO** [comment]
Ok I found the reason. It is caused by a conflict with Fractionate Everything (by MengLei). I am talking to him/her now but before any one of us update our mod, you will have to uninstall one of these two mods. or, live with most of the mms unuseable.

**Comment by jinxOAO** [comment]
MengLei said he will update soon. Please wait for the new version of Fractionate Everything.
